### ISSUE TITLE
Emphasoft review

### ISSUE THREAD

**Issue by EvgenyOrekhov** [Ivsmcrew/Enphasoft#1]
It's great that Vercel deployment is set up!

# Issues

1. Authentication gets lost after a page refresh
2. When user is on `/users` page, after authentication they get redirected to the home page (it would be better to keep the user on the same page)
3. "Delete" button can be clicked even when no user is selected, which executes an invalid `DELETE users/null/` request
4. Filtering and sorting gets lost after adding/editing/deleting a user (`filteredAndSortedUsers` should not be in state, it should be derived from `users`, see https://redux.js.org/style-guide/#keep-state-minimal-and-derive-additional-values)
5. Server errors (including errors for each form field) don't get shown to the user
6. Some text is illegible because it has low contrast against background

# Code suggestions

1. `AddForm/helper.js`, `EditForm/helper.js`, and `LoginForm/helper.js` files have duplicate code, should combine them into a single common `helpers.js` file

**Comment by Ivsmcrew** [comment]
Hi, @EvgenyOrekhov! Thank you very much for the comprehensive feedback. All the changes are in corresponding pull request! I was not sure that pushing without your checking is right and good practice... So you can see changes only in local deployment, due to Vercell is configured on main branch
